### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by payerle** [PyMumps/pymumps#13]
I am trying to build PyMumps version 0.3.2 for python 3.7.7 on an RHEL8 system.
(Indeed, I am trying to write a Spack (https://spack.io) recipe to do so).  I have Mumps 5.2.0 installed on the system.

I am able to build PyMumps, but when I try to run a simple python test code (to solve Ax=b for x given A,b), I receive an undefined symbol error:
```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/spack-software/2020.05.14/linux-rhel8-ivybridge/gcc-8.4.0/py-pymumps-0.3.2-dieeka4jysowuodru5ugkrgendaughju/lib/python3.7/site-packages/mumps/__init__.py", line 2, in <module>
    import mumps._dmumps
ImportError: /software/spack-software/2020.05.14/linux-rhel8-ivybridge/gcc-8.4.0/mumps-5.2.0-2vqesppnxfqdnx5xc3s262onaa6oyqfg/lib/libdmumps.so: undefined symbol: __mumps_ooc_common_MOD_low_level_strat_io
```

The nm command does indeed show that libdmumps.so has an undefined variable reference to __mumps_ooc_common_MOD_low_level_strat_io, which is defined as a global (external) BSS symbol in libmumps_common.so.  (Both libraries are part of the installed Mumps package).  As a test,  I tried setting LD_PRELOAD to preload the libmumps_common.so, and with that the python test works as expected.  But that is not a real solution.

I am able to construct and successfully run a similar Fortran test code for Mumps (using the same Mumps installation)(again solving Ax=b for x), and this works as expected (without needing to mess with LD_PRELOAD).  Based on this, it looks to me like the issue is with PyMumps and not Mumps.

I have tried the PyMumps build again, after making a small modification to setup.py:
```console
diff -Naur spack-src/setup.py spack-src.patched/setup.py
--- spack-src/setup.py  2018-11-05 16:57:21.000000000 -0500
+++ spack-src.patched/setup.py  2020-10-26 11:23:41.363767947 -0400
@@ -35,7 +35,7 @@
         Extension(
             'mumps._dmumps',
             sources=['mumps/_dmumps.pyx'],
-            libraries=['dmumps'],
+            libraries=['dmumps', 'mumps_common'],
         ),
     ],
     install_requires=['mpi4py'],
```
I.e: adding a dependency on the 'mumps_common' library.

When I do this, the Python module again builds, and when I run the same test code it behaves as expected --- the python code runs w/out the undefined symbol load error, and produces the expected result.

I confess I am not very familiar with Mumps/PyMumps, but it appears to me that the setup.py should be adding this additional library dependency.

**Comment by sdrave** [comment]
Hi @payerle! Interesting, on my Debian stable machine dmumps has mumps_common as a link dependency, so the problem does not occur.  Seems like the Debian patches add the dependency whereas as the spack package does not (I think it should). In any case, it does not hurt to explicitly add the dependency on mumpy_common for the pymumps extension module, so I just pushed your suggested change. Thanks!
