### ISSUE TITLE
Installing pymumps with mumps from conda-forge

### ISSUE THREAD

**Issue by santiagoropb** [PyMumps/pymumps#5]
Hi,

I tried installing the package and even though the installation is successful I get an error when running the example. I install the dependencies with conda-forge (MUMPS5.1.2). The error seems to be happening when linking with the share library:

dlopen(_dmumps.cpython-36m-darwin.so, 2)
Symbol not found: ___mumps_fac_descband_data_m_MOD_inode_waited_for

Is there an easy fix? Does pymumps work with other all version 

Thanks

**Comment by jbweston** [comment]
I also get a similar problem when using mumps from conda forge:

```
(pm) jbw@broadway ~  $ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mumps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jbw/.local/miniconda/lib/python3.6/site-packages/PyMUMPS-0.3.2-py3.6-linux-x86_64.egg/mumps/__init__.py", line 2, in <module>
    import mumps._dmumps
ImportError: /home/jbw/.local/miniconda/lib/python3.6/site-packages/PyMUMPS-0.3.2-py3.6-linux-x86_64.egg/mumps/_dmumps.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __mumps_ooc_common_MOD_ooc_vaddr
```

it's not the same symbol, but I suspect the problems may be similar

**Comment by sdrave** [comment]
I am currently looking into this. The main issue seems to be that the conda mumps package only ships static libraries and that all dependencies of mumps need to be correctly specified in `setup.py`. There is also an `mumps-mpi` package which, for some strange reason ships shared libraries. Using that leads to segfaults ..

**Comment by jbweston** [comment]
When I inspect the shared library that PyMUMPS builds (`_dmumps.cpython....`) I see the following things:

```
(pm) jbw@broadway pymumps (master) $ ldd mumps/_dmumps.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffd16f29000)
	libpython3.6m.so.1.0 => /home/jbw/.local/miniconda/lib/libpython3.6m.so.1.0 (0x00007f5fd4f94000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fd4f42000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fd4d85000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5fd4d80000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5fd4d7b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5fd4d71000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fd4bdb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5fd5648000)
```

```

(pm) jbw@broadway pymumps (master) $ nm -u mumps/_dmumps.cpython-36m-x86_64-linux-gnu.so  | grep mumps
                 U mumps_abort_
                 U mumps_allreducei8_
                 U mumps_amd_elt_
                 U mumps_ana_h_
                 U mumps_assign_mapping_
                 U mumps_assign_pivnul_list_
                 U mumps_assign_sym_perm_
                 U mumps_assign_uns_perm_
                 ...
```

This tells me that PyMUMPS was not correctly linked against mumps because there's no entry telling the dynamic linker to pull in any mumps-related libraries, and all the mumps-related symbols are undefined.

My guess is that we are not linking against `mumps_common`, because I don't see any double-precision-specific undefined symbols

**Comment by sdrave** [comment]
Ok, so if building pymumps with

```python
libraries=['dmumps', 'mumps_common', 'esmumps', 'metis', 'scotch', 'openblas', 'mpiseq', 'pord']
```
in `setup.py` (all libraries needed) resolves all symbols for the `mumps` package. However, then I am getting the same segfaults as with `mumps-mpi`.

**Comment by sdrave** [comment]
I am on Debian stable, which still has mumps-4.10. I guess the bindings don't work with newer mumps. Will take a look.

**Comment by jbweston** [comment]
Yeah linking against mumps is a bit of a black art. It seems that our "mumpy" wrapper works when linking both against Debian mumps and against Conda mumps. I should reserve some time to pull the mumpy code into PyMUMPS like I said I would.

**Comment by sdrave** [comment]
So at first sight it doesn't have anything to do with the mumps version. I just installed the mumps-5.1.2 source package from sid and things seem to be working fine. Seems to be something specific to anaconda.

**Comment by santiagoropb** [comment]
@sdrave what do you mean you installed the package from sid? Does that mean you are just building it from source? It would be convenient to get it working with the distributed binaries from conda since it will simplify significantly the building process. Especially, given that mumps from conda-forge distributes windows, linux and macos.

**Comment by santiagoropb** [comment]
@jbweston I saw you are a contributor for the conda-forge recipe of mumps. Would it be possible to add pymumps in the mumps recipe to overcome the linking issue? I suppose the right way to go with would be to create a pymumps recipe and have your mumps in the requirements.

**Comment by sdrave** [comment]
@santiagoropb, 'sid' is the name of the Debian unstable repository. Are you using the mumps or mumps-mpi package?

**Comment by santiagoropb** [comment]
Thanks! I am using mumps. At this point I don't really care about using pymumps in parallel just want to test some of the features of the serial version. I believe there have been significant improvements from 4.10 to 5.1.2 so I want to run some benchmark problems that work fine with HSL/ma27 but fail with mumps-4.10. Thanks for the initiative with pymumps. I believe efficient open-source reliable linear solvers  are needed in python.

**Comment by sdrave** [comment]
Ok, so the reason for my segfaults with anaconda was that pymumps' setup.py included the system mumps headers instead of the ones shipped with anaconda, and those were of the wrong version ..

@santiagoropb, could you try to change the linked libraries in setup.py to
```
libraries=['dmumps', 'mumps_common', 'esmumps', 'metis', 'scotch', 'openblas', 'mpiseq', 'pord']
```
and then install pymumps by hand (using `python setup.py install`)? On my machine this seems to work.

**Comment by santiagoropb** [comment]
@sdrave that works for me too!

**Comment by sdrave** [comment]
See #7.
