### ISSUE TITLE
conda recipe

### ISSUE THREAD

**Issue by santiagoropb** [PyMumps/pymumps#7]
@sdrave I would like to use pymumps within an optimization project that we have with Pyomo (Sandia National Labs). To facilitate the installation of pymumps I created a conda-forge recipe that makes it easier to installl pymumps. to do that I have forked your repo, added a couple of things to setup.py and written a meta.yml file for the recipe. I would like to get your permission to do this before the pull request to conda-forge is merged into feedstock. I am currently listing myself as the maintainer but if you are interested in the recipe too I could list you as a maintainer as well. Also the source is obtained from my fork but if it is of you interest we could pull that from your repo instead (we will need to merge my changes).

Thanks

**Comment by sdrave** [comment]
Hi @santiagoropb, sorry for the late reply.

I think it would be very desirable to build the code-forge package from the official pymumps repo. Would it also be ok for you if `libraries`, `include_dirs` and `library_dirs` are made configurable via environment variables? IMHO that would be cleaner than manually parsing the command line. If this is fine with you, I can implement this soon.

If I remember correctly, the MPI distributed version of mumps can also be installed from conda-forge. It would be nice if this was supported by the pymumps recipe as well (in which case `libraries` probably needs to be adapted).

Yes, please add me as a maintainer of the recipe. At least I would update the recipe when there is a new pymumps release.

**Comment by santiagoropb** [comment]
Sounds good. Please send me an email to santiagoropb@gmail.com to communicate via email.

**Comment by sdrave** [comment]
The conda recipe is [here](https://github.com/conda-forge/pymumps-feedstock).
