### ISSUE TITLE
Install with statically linked libraries

### ISSUE THREAD

**Issue by Robbybp** [PyMumps/pymumps#8]
I'm installing with MUMPS built from source, which by default builds static libraries. I can link these libraries with Pymumps if I compile them with -fPIC, but there is currently no way to specify libraries to link statically, which I believe should be done via the `extra_objects` argument in `Extension`. I think this could also be accomplished by prepending the location of my static MUMPS libraries to `PYMUMPS_SETUP_LIBRARY_DIRS`, but this would not be reliable if I had static and dynamic libraries in the same location.

**Comment by sdrave** [comment]
See #9/#10.
